#!/bin/bash
echo "[hook_script] $0"

chown root:root /srv/etc/monitrc
chmod 600 /srv/etc/monitrc

chown -R www-data:www-data /srv/http/{.aria2,aria2-download,ariang}
echo > /srv/log/aria2.log
chown www-data:www-data /srv/log/aria2.log

touch /srv/log/v2ray-{access,error}.log
chown nobody:nobody /srv/log/v2ray-access.log
chown nobody:nobody /srv/log/v2ray-error.log
for file in server-v2tls.key server-v2tls.crt; do
    if [ -f "/srv/etc/ssl-certs/$file" ]; then
        chown nobody:nobody /srv/etc/ssl-certs/$file
    fi
done

if [ -x "/srv/etc/update_v2ray" ]; then
    /srv/etc/update_v2ray
fi
