#!/bin/bash
echo "[hook_script] $0"

chown root:root /srv/etc/monitrc
chmod 600 /srv/etc/monitrc

chown -R www-data:www-data /srv/http/{.aria2,aria2-download,ariang}
echo > /srv/log/aria2.log
chown www-data:www-data /srv/log/aria2.log

touch /srv/log/v2ray-{access,error}.log
chown nobody:nobody /srv/log/v2ray-access.log
chown nobody:nobody /srv/log/v2ray-error.log
for file in server-v2tls.key server-v2tls.crt; do
    if [ -f "/srv/etc/ssl-certs/$file" ]; then
        chown nobody:nobody /srv/etc/ssl-certs/$file
    fi
done

/usr/bin/install_v2ray.sh "5.1.0"

if [ ! -d "/srv/headscale" ]; then
    mkdir /srv/headscale
fi
chown headscale:www-data /srv/headscale
touch /srv/log/headscale.log
chown headscale:www-data /srv/log/headscale.log
if [ ! -f "/srv/etc/headscale-config.yaml" ]; then
    wget -O /srv/etc/headscale-config.yaml https://github.com/juanfont/headscale/raw/v0.17.0-beta4/config-example.yaml
    sed -i -e 's|/var/lib/headscale/|/srv/headscale/|' -e 's|/var/run/|/srv/headscale/|' \
        /srv/etc/headscale-config.yaml
fi

/usr/bin/install_headscale.sh "0.17.0-beta4"
