#!/bin/bash

V2RAY_LOCATION_ASSET=${V2RAY_LOCATION_ASSET:-/etc/v2ray}
V2RAY_ZIP_URL=${V2RAY_ZIP_URL:-https://github.com/v2fly/v2ray-core/releases/download/v%s/v2ray-linux-64.zip}

# update v2ray
V2RAY_NEW_VERSION=4.36.2

V2RAY_CACHE_ZIP=/srv/v2ray-linux-64-v${V2RAY_NEW_VERSION}.zip

if [[ "$V2RAY_NEW_VERSION" != "$V2RAY_VERSION" ]]; then
    echo "==> update v2ray: $V2RAY_VERSION -> $V2RAY_NEW_VERSION ..."
    mkdir /tmp/v2r
    if [ ! -f "${V2RAY_CACHE_ZIP}" ]; then
        wget -P /srv -O ${V2RAY_CACHE_ZIP} `printf "${V2RAY_ZIP_URL}" ${V2RAY_NEW_VERSION}`
    fi
    if [ -f ${V2RAY_CACHE_ZIP} ]; then
        unzip ${V2RAY_CACHE_ZIP} -d /tmp/v2r/ \
        && install -Dm755 /tmp/v2r/v2ray /usr/bin/v2ray \
        && install -Dm755 /tmp/v2r/v2ctl /usr/bin/v2ctl \
        && install -Dm755 /tmp/v2r/geoip.dat ${V2RAY_LOCATION_ASSET}/geoip.dat \
        && install -Dm644 /tmp/v2r/geosite.dat ${V2RAY_LOCATION_ASSET}/geosite.dat \
        && install -Dm644 /tmp/v2r/config.json ${V2RAY_LOCATION_ASSET}/config.json
    fi
    echo "==> clean ..."
    rm -rf /tmp/v2r
fi
